---
# handlers file for pbis
  - name: copy config dump to tmp dir
    template:
      src: dump.j2
      dest: "{{ pb_config_path }}"

  - name: import powerbroker config
    command: /opt/pbis/bin/config --file "{{ pb_config_path}}/{{ pb_config_file }}"
    register: config
    failed_when: config.rc == 1

  - name: clean up
    file:
      path: "{{ pb_config_path}}/{{ pb_config_file }}"
      state: absent
