--- #remove centrify main.yaml
    - name: check os
      assert:
        that: 
          - ansible_os_family == 'RedHat'
          - "ansible_distribution != 'CentOS'"
      tags: get_os

    - name: check if centrify is installed
      yum:
        name: '{{ item }}'
        state: present
      register: installed
      with_items: '{{ packages }}'
      tags: chkinst

    - name: get centrify groups
      shell: adquery group -M | tr " " "_" | tr [:upper:] [:lower:]
      register: ad_groups
      tags: getinfo

    - name: copy centrify groups to host
      template:
        src: centrify_grps.j2
        dest: "/var/tmp/centrify_grps"
      tags: getinfo

    - name: leave domain
      command: adleave --remove -u '{{ pb_username }}' -p '{{ pb_password }}'
      register: adleave_out

    - name: check password
      debug:
        var: pb_password
      tags: pschk

    - name: remove centrify rpms
      yum:
        name: '{{ item }}'
        state: absent
      with_items: '{{ packages }}'
      tags: chkinst
