--- #remove centrify main.yaml
    - name: check os
      assert:
        that: 
          - ansible_os_family == 'RedHat'
          - ansible_distribution != 'CentOS'
      tags: get_os

    - name: check if centrify is installed
      shell: rpm -qa | grep -i centrify
      register: inst
      failed_when: inst.stdout == ''
      tags: chkinst

    - name: get centrify groups
      shell: adquery group -M | tr " " "_" | tr [:upper:] [:lower:]
      register: ad_groups
      tags: getinfo

    - name: copy centrify groups to host
      template:
        src: centrify_grps.j2
        dest: "/var/tmp/centrify_grps"
      tags: getinfo

    - name: leave domain
      command: adleave --remove -u {{ pb_username }} -p {{ pb_password }}
      no_log: true
      tags: leavedom

    - name: check vars
      debug:
        var: pb_password
      tags: varchk

    - name: remove centrify
      command: rpm -e --nodeps {{ item }}
      with_items: '{{ inst.stdout_lines }}'
      tags: rm
