---
  - name: import gpg key
    rpm_key:
      state: present
      key: '{{ ppt_key }}'

  - name: install puppet agent
    yum:
      name: 
        - puppet-agent
      state: latest
    notify:
      - copy config
      - set puppet to start at boot
      - puppet agent force
