---
# tasks file for pbis
  - name: install powerbroker from spacewalk
    yum:
      name: pbis-open
      state: latest
      disable_gpg_check: yes

  - name: check the domain status
    shell: /opt/pbis/bin/get-status | grep -q "{{ pb_domain_netbios }}"
    ignore_errors: yes
    register: domain_status

  - name: join the domain if needed
    command: /usr/bin/domainjoin-cli join {{ pb_domain_fqdn }} --ou {{ pb_ou }} {{ pb_username }} {{ pb_password }}
    when: domain_status.rc != 0

  - name: copy config dump to tmp dir
    template:
      src: dump.j2
      dest: "{{ pb_config_path }}"

  - name: import powerbroker config
    command: /opt/pbis/bin/config --file "{{ pb_config_path}}/{{ pb_config_file }}"
    register: config
    failed_when: config.rc == 1

  - name: clean up
    file:
      path: "{{ pb_config_path}}/{{ pb_config_file }}"
      state: absent