---
# tasks file for pbis
  - name: install powerbroker from spacewalk
    yum:
      name: pbis-open
      state: latest
      disable_gpg_check: yes

  - name: check the domain status
    shell: /opt/pbis/bin/get-status | grep -q "{{ pb_domain_netbios }}"
    ignore_errors: yes
    register: domain_status

  - name: join the domain if needed
    command: /usr/bin/domainjoin-cli join {{ pb_domain_fqdn }} --ou {{ pb_ou }} {{ pb_username }} {{ pb_password }}
    when: domain_status.rc != 0
    notify:
      - copy config dump to tmp dir
      - import powerbroker config
      - clean up
