---
# tasks file for powerbroker
  - name: install powerbroker from spacewalk
    yum:
      name: pbis-open
      state: latest
      disable_gpg_check: yes

  - name: check the domain status
    shell: /opt/pbis/bin/get-status | grep -q "{{ pb_domain_netbios }}"
    ignore_errors: yes
    register: domain_status

  - name: join the domain if needed
    command: /usr/bin/domainjoin-cli join --ou {{ pb_ou }} {{ pb_domain_fqdn }} {{ pb_username }} {{ pb_password }}
    when: domain_status.rc != 0

  - name: config pbis domain
    command: /opt/pbis/bin/config AssumeDefaultDomain {{ pb_assume_default_domain }}
    register: config_domain
    failed_when: config_domain.rc == 1
    when: pb_assume_default_domain is defined

  - name: config pbis shell
    command: /opt/pbis/bin/config LoginShellTemplate {{ pb_login_shell_template }}
    register: config_shell
    failed_when: config_shell.rc == 1
    when: pb_login_shell_template is defined

  - name: config pbis homedirtemplate
    command: /opt/pbis/bin/config HomeDirTemplate {{ pb_homedir_template }}
    register: config_home
    failed_when: config_home.rc == 1
    when: pb_homedir_template is defined

  - name: config pbis userdomainprefix
    command: /opt/pbis/bin/config UserDomainPrefix {{ pb_domain_netbios }}
    register: config_prefix
    failed_when: config_prefix.rc == 1
    when: pb_domain_netbios is defined

  - name: config pbis SpaceReplacement
    command: /opt/pbis/bin/config SpaceReplacement {{ pb_space_replacement }}
    register: config_space_r
    failed_when: config_space_r.rc == 1
    when: pb_space_replacement is defined