---
# tasks file for powerbroker
  - name: import gpg key
    rpm_key:
      state: present
      key: '{{ pb_key }}'
    tags: pb_install

  - name: install powerbroker from spacewalk
    yum:
      name: pbis-open
      state: latest
    tags: pb_install

  - name: check the domain status
    shell: /opt/pbis/bin/get-status | grep -q "{{ pb_domain_netbios }}"
    ignore_errors: yes
    register: domain_status
    tags: pb_reg

  - name: copy config
    template:
      src: dump.j2
      dest: "{{ pb_config_path}}/{{ pb_config_file }}" 
    when: domain_status.rc != 0
    tags: pb_reg
    notify: 
      - import config
      - clean up
      - join domain

  - name: set requiremembership if run again
    command: /opt/pbis/bin/config RequireMembershipOf {{ pb_require_membership_of | join(" ") }}
    register: requiremembership
    failed_when: requiremembership.rc == 1
    when: pb_require_membership_of is defined
    tags: pb_memb

  - name: debug password
    debug:
      var: pb_password
    tags: pb_pass