---
# tasks file for common
- name: ensure sudoers dropin exists
  file:
    path: '{{ sudoers_dropin_dir }}'
    state: directory
    mode: 0750

- name: enable passwordless sudo
  template:
    src: 'nopasswd.j2'
    dest: '{{ sudoers_dropin_dir }}/{{ sudo_file_name }}'
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'

- name: 'ensure sudoers dropin directory is #includedir-ed'
  lineinfile:
    dest: '{{ sudoers_cfg_file }}'
    regexp: '^#includedir\s+{{ sudoers_dropin_dir }}'
    line: '#includedir {{ sudoers_dropin_dir }}'

