---
# tasks file for fix-perms
- name: find the files first
  find: 
    paths: "/tmp/"
  register: filez

- debug:
    var: '{{ item }}'
  with_items: filez.files.path

#- name: find files owned by user 
#  stat:
#    path: /tmp/*
#  register: st_out

#- debug:
#    var: st_out.stat.path
#  when: st_out.stat.pw_name == fx_owner

- name: fix file perms
  file:
    path: '{{ fx_file }}'
    owner: '{{ fx_owner }}'
    group: '{{ fx_group }}'